<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-ADS3JVM" failures="1" tests="4" name="Test" time="41.825" errors="0" timestamp="2025-01-10T20:04:59 IST">
  <testcase classname="frameWork.ErrorValidation" name="sumitOrder" time="0.743">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;Incorrect email or password.&amp;gt; but was:&amp;lt;unknown error occured&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<Incorrect email or password.> but was:<unknown error occured>
at frameWork.ErrorValidation.sumitOrder(ErrorValidation.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- sumitOrder -->
  <testcase classname="frameWork.StandAlone" name="sumitOrder" time="6.971"/>
  <testcase classname="frameWork.StandAlone" name="sumitOrder" time="7.199"/>
  <testcase classname="frameWork.StandAlone" name="myOrdersTest" time="3.055"/>
</testsuite> <!-- Test -->
